name: Monitor Metrobus CDMX

on:
  schedule:
    # 9:00 AM CDMX (15:00 UTC) - Lunes a Viernes
    - cron: '0 15 * * 1-5'

    # 7:30 PM CDMX (01:30 UTC del día siguiente) - Lunes a Viernes
    - cron: '30 1 * * 1-5'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          USUARIO_API_KEY: ${{ secrets.USUARIO_API_KEY }}
          SENHA_API_KEY: ${{ secrets.SENHA_API_KEY }}
        run: python alerta_metrobus.py
