name: Monitor Metrobus CDMX

on:
  schedule:
    # 7:30 AM CDMX (13:30 UTC), de Lunes a Viernes (1 al 5)
    - cron: '30 10 * * 1-5'
    
    # 5:50 PM CDMX (23:50 UTC), de Lunes a Viernes (1 al 5)
    - cron: '20 22 * * 1-5'
    
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          USUARIO_API_KEY: ${{ secrets.USUARIO_API_KEY }}
          SENHA_API_KEY: ${{ secrets.SENHA_API_KEY }}
        run: python alerta_metrobus.py
